### ISSUE TITLE
can't display image in BioCollect

### ISSUE THREAD

**Issue by mathieuLU** [biodiversitydata-se/biocollect#165] opened 2021-10-19 06:52 UTC
On the home page : https://biocollect.biodiversitydata.se/sft
can't display the logo on the top left part of the screen

I guess it's because of the https change yesterday.
URL targetted is https://ecodata.bioatlas.se/document/download?filename=/2020-12/0_sft_logo.png

My guess would be to change the URL in the ecodata configuration file, from http to https

```
ubuntu@ecodata-biodiv:/data/ecodata/config$ cat ecodata-config.properties | grep download
app.uploads.url=http://ecodata.biodiversitydata.se/document/download?filename=/
#URL to use to download asynchronously produced files
async.download.url.prefix=http://biocollect.biodiversitydata.se/download/
```

To be tried....

**Comment by magdziarek** [comment] 2021-10-19 10:28
It's back. I didn't change anything in the code but only in the hub settings. 
go to /admin/tools and MANAGE HUBS - tab HEADER - delete the logo that's not displayed correctly, add the target logo, save. The URL comes from the database db.hub.find({urlPath:"sft"}, {logoUrl: 1})
The URLs for the other logos, in the footer, also come from the DB 
db.hub.find({urlPath:"sft"}, {"templateConfiguration.footer": 1})
I will try to change it.

**Comment by magdziarek** [comment] 2021-10-19 12:43
@mathieuLU  I can imagine why they did it this way - possibly because of the directory structure - all images are saved in a folder with the date when they were uploaded. The URL is changed somewhere on the backend. So manipulating the URL to get the right path would maybe be error prone? 
I tried for a few hours. The issue is not there anymore, but it might resurface if something changes like now, they will have to be changed manually using the UI (deleted and uploaded again) or changed in the database. Otherwise, I could spend another couple of hours trying to change the structure of the directory where images are saved... :/

**Comment by magdziarek** [comment] 2021-10-19 13:16
I am almost there but making this better would require:
Solution 1:
We change the directory structure and instead of organizing files by date uploaded and having urls like:
http://canmove-dev.ekol.lu.se:8080/ecodata/document/download?filename=/2021-10/SBDI-vit-med-text.png
we would organize them by the type of file and have: 
http://canmove-dev.ekol.lu.se:8080/ecodata/document/download?filename=/images/SBDI-vit-med-text.png

Solution 2:
We keep the directory structure and concatenate the directory partition format /2021-10/ to the name of the file and then we would be able to use the rest of the url from the config...

**Comment by mathieuLU** [comment] 2021-10-20 07:27
it seems that your final message is not complete.

Anyway I think we should avoid the solution 1. Solution 2 seems good, using the url from config. But maybe its not our role to do that.
Donät spend any time with it

Maybe that could be an issue to post on the ALA branch of Ecodata ? Becase it makes no sense for us to change it if they don't do it as well

**Comment by magdziarek** [comment] 2021-10-20 07:48
The image is displayed now so I am closing this issue. If it happens again then you can refer to this to know where it's coming from.

**Closed as completed by magdziarek** 2021-10-20 07:48 UTC
