### ISSUE TITLE
Edit Biocollect site => could not save site

### ISSUE THREAD

**Issue by mathieuLU** [biodiversitydata-se/biocollect#177] opened 2021-12-22 07:32 UTC
https://biocollect.biodiversitydata.se/sft/site/editSystematic/feff3d89-cfa0-4f3b-98d9-1e25ce52729b

"Could not save site"

biocollect side
java.io.IOException: Server returned HTTP response code: 500 for URL: https://ecodata.biodiversitydata.se/ws/site/feff3d89-cfa0-4f3b-98d9-1e25ce52729b
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)

ecodata side
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class au.org.ala.ecodata.GeometryUtils
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1055)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)

java.lang.NoClassDefFoundError: Could not initialize class au.org.ala.ecodata.GeometryUtils
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)

**Comment by mathieuLU** [comment] 2021-12-22 07:34
maybe only the correct userId can fix it ?

**Comment by ekol-ali** [comment] 2021-12-29 15:12
There seems to be a system in when this works or not! You can edit routes if there is only one coordinate. It always fails when the route has coordinates for all 20 points.

**Comment by ekol-ali** [comment] 2021-12-30 11:36
There was a message from a new surveyor today, Patrick Degerman, that after entering 20 points of a new route, he got the message "Could not save site". Maybe related to this issue?

**Comment by mathieuLU** [comment] 2022-01-05 18:56
to keep you informed :
I identified the bug, i already spent some hours trying to debug it. I'll find something. Maybe I'll call Aleksandra for help since its related to one of her latest modification

**Comment by ekol-ali** [comment] 2022-01-05 19:57
Finding the problem is a good start, good luck with debugging it.

**Comment by mathieuLU** [comment] 2022-01-06 00:08
I found a temporary fix. Which I'm not happy with. But at least I moved forward and I have something to send to the Australian team.

I store my details there. Even if it's greek to you. Don't worry, it's greek to me as well (and i'm sure your greek is better than mine!)

error thrown when editing/creating a site with points on Biocollect : 
biocollect side =>
`java.io.IOException: Server returned HTTP response code: 500 for URL: http://canmove-dev.ekol.lu.se:8080/ws/site/`

ecodata side : 
```
org.hsqldb.DatabaseURL.parseURL(Ljava/lang/String;ZZ)Lorg/hsqldb/persist/HsqlProperties;. Stacktrace follows:

java.lang.reflect.InvocationTargetException: null
        at org.grails.core.DefaultGrailsControllerClass$ReflectionInvoker.invoke(DefaultGrailsControllerClass.java:211)
        at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)
```
```

      at au.org.ala.ecodata.GeometryUtils.<clinit>(GeometryUtils.groovy:26)
        at java.lang.Class.forName(Class.java:348)
        at au.org.ala.ecodata.SiteService.setCentroidAsExtent(SiteService.groovy:722)
 
```
 
ths is the error thrown on the first click. on the second try, it refers only to geometryUtils

My  understanding : 

to create/edit a site, it goes through the SiteService.groovy, that uses our GeometryUtils lib.  It seems that the geometryUtils uses a library called hsqldb. According to build.gradle, we use the version 2.3.1
`runtime "org.hsqldb:hsqldb:2.3.1"`

for some reason, the version 1.8.1.1 is used as well.

when we compile, the dependency appears twice : 
```
build/.dependencies:100:- file:/home/radar/.gradle/caches/modules-2/files-2.1/org.hsqldb/hsqldb/2.3.1/bd7153caa30958e1c64a3dd38b93e5a7442d9a0e/hsqldb-2.3.1.jar
build/.dependencies:171:- file:/home/radar/.gradle/caches/modules-2/files-2.1/hsqldb/hsqldb/1.8.1.1/4567bac9372cb6e4f28b6127655589dedf10425d/hsqldb-1.8.1.1.jar
```

the strangest thing is that the error we have (org.hsqldb.DatabaseURL.parseURL(Ljava/lang/String;ZZ)) is not triggered in test mode (with grails run-app). But it's triggered in production (tomcat).
According to the logs, in dev/test only the library 2.3.1 is loaded. But when I look in the WEB-INF/lib in tomcat, I can see both the libraries 2.3.1 and 1.8.1.1

A temporary fix (which is of course not correct at all) is to remove the library ROOT/WEB-INF/lib/hsqldb-1.8.1.1.jar
I guess it's used somewhere else and will create other problems...

**Comment by mathieuLU** [comment] 2022-01-06 11:21
I got an answer from Chris@ala today. I already spent several hours on it, without any succes

_Hi Mathieu,

Happy new year to you as well, and I am in complete agreement with your hope for 2022!

I don’t have time to do any investigation about this, but the issue is likely geotools, as it’s the only component that uses hsqldb (apart from the default grails dependency).

Option 1:

    Have a look at: https://github.com/AtlasOfLivingAustralia/ecodata/tree/features/issue718 which upgrades geotools.  Note: untested.

Option 2:

    Set the version in build.gradle to match the version expected by geotools rather than the grails default.

Cheers,
Chris_

**Comment by mathieuLU** [comment] 2022-01-06 11:37
i give up today after 3 more hours. Here is what I answered to Chris

_Thanks for your answer Chris
I know that we're close but I still can't make it work. I tried the 2 options :
1) specific branch with all the modifications listed here => https://github.com/AtlasOfLivingAustralia/ecodata/commit/f8d4527ce0f65f45afdcdd568b567afed6f27411
same result
2) trying different options, with different versions of hsqldb. Same result as well
the very strange thing is that it works fine when i use the dev environement (grails run-app). But it fails with tomcat. And when i delete the lib in tomcat (hsqldb-1.8.1.1.jar), then it works with tomcat as well (but it creates maybe other problems... not sure if this hsqldb-1.8.1.1.jar is used elsewhere).

this 1.8.1.1 is coming with the grails core maven repo https://repo.grails.org/ui/native/core/hsqldb/hsqldb/1.8.1.1

Maybe I could try to find a way to exclude the hsqldb-1.8.1.1.jar to be downloaded ?

All your inputs are welcome_

**Comment by mathieuLU** [comment] 2022-01-06 15:42
ok so in the end I found a better fix, that is still temporary. But the discussion is ongoing with the australian Team. Åke, I let you check on the server, and close the issue if it seems ok to you. I was able to create a site so I'm confident that it's ok ;-)

If needed I will reopen it to more forward with the new elements coming from the ALA team.

I will store there as well my latest modifications to find it in case the problem reoccurs

**Comment by mathieuLU** [comment] 2022-01-06 15:45
What I've done in the end :
excluding the hsqldb-1.8.1.1 when generating the war file. See the ecodata commit there : https://github.com/biodiversitydata-se/ecodata/commit/ecbc270dcc18bb7dc4407f7005ce6783f09f57a0

Before doing this, I also tried several modifications in the build.gradle. And also tried what Chris suggested (https://github.com/AtlasOfLivingAustralia/ecodata/commit/f8d4527ce0f65f45afdcdd568b567afed6f27411)
These tests based on Chris modifications on geotools are stashed in the branch : lusm-grails4-master-hsql-update

**Comment by ekol-ali** [comment] 2022-01-06 17:29
I started with changing some route names that didn't work before (issue #185). That worked nicely. I also managed to change the name of my own route TORNA HÄLLESTAD. 
**However**, when trying to add explanatory text to some points of that route of mine, I got the "could not be saved" note.

**Comment by mathieuLU** [comment] 2022-01-10 10:15
I tried this morning and it worked (with this example https://biocollect.biodiversitydata.se/sft/site/editSystematic/c52f9cd5-24a4-435c-9b6f-6d076214063c)

Please send me an example that does not work, so I could check in details this specific case

**Comment by ekol-ali** [comment] 2022-01-10 10:22
Great! What I failed with 4 days ago, now worked. I could add descriptive text to point 1 of my point count route.

**Comment by ekol-ali** [comment] 2022-01-10 10:22
https://biocollect.biodiversitydata.se/sft/site/editSystematic/5ead1d4c-f3be-4308-86e9-667bc15163da

**Comment by mathieuLU** [comment] 2022-01-10 10:25
ok strange 
I let you close the issue if it seems ok to you

**Comment by ekol-ali** [comment] 2022-01-10 12:41
I hereby close this issue - well done Mathieu!

**Closed as completed by ekol-ali** 2022-01-10 12:41 UTC
